import os
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "data" / "Company profile"
DEST_DIR = ROOT / "public" / "profiles"

# Map source PDF names (case-insensitive search) to developer slugs
MAPPING = {
    "hassan allam corporate profile": "hassan-allam-properties",
    "hyde park company profile": "hyde-park",
    "lmd": "lmd",
    "la vista": "la-vista-developments",
    "mip - company profile": "misr-italia",
    "madinet masr-company profile": "madinet-masr",
    "ora developers ii company profile": "ora-developers",
    "sodic company profile": "sodic",
    "tatweer company profile": "tatweer-misr",
    "water way": "the-waterway-developments",
}

def main():
    print("Copying and renaming company profiles to public assets...")
    if not DEST_DIR.exists():
        DEST_DIR.mkdir(parents=True, exist_ok=True)
        print(f"Created destination directory at {DEST_DIR}")

    if not SOURCE_DIR.exists():
        print(f"Error: Source directory {SOURCE_DIR} does not exist!")
        return

    files = list(SOURCE_DIR.glob("*.pdf"))
    copied_count = 0

    for f in files:
        # Match by filename
        name_lower = f.stem.lower().strip()
        matched_slug = None
        
        # Check for fuzzy match in mapping keys
        for key, slug in MAPPING.items():
            if key in name_lower or name_lower in key:
                matched_slug = slug
                break
                
        if matched_slug:
            dest_file = DEST_DIR / f"{matched_slug}.pdf"
            shutil.copy2(f, dest_file)
            try:
                print(f"Copied: {matched_slug}.pdf")
            except:
                pass
            copied_count += 1
        else:
            # Fallback slugify for unknown files
            slugified = name_lower.replace(" ", "-").replace("_", "-")
            # Remove non-ascii
            slugified = "".join([c for c in slugified if ord(c) < 128])
            dest_file = DEST_DIR / f"{slugified}.pdf"
            shutil.copy2(f, dest_file)
            try:
                print(f"Copied (fallback name): {slugified}.pdf")
            except:
                pass
            copied_count += 1

    print(f"Successfully copied {copied_count} company profiles to {DEST_DIR}!")

    # 4. Generate src/data/profiles.generated.ts
    generated_file = ROOT / "src" / "data" / "profiles.generated.ts"
    active_slugs = []
    for f in DEST_DIR.glob("*.pdf"):
        active_slugs.append(f.stem)
    
    active_slugs.sort()
    
    ts_content = f"""// Auto-generated by scripts/copy-profiles.py - do not edit by hand.
export const developersWithProfiles: string[] = {repr(active_slugs)};
"""
    
    with open(generated_file, "w", encoding="utf-8") as f_out:
        f_out.write(ts_content)
    print(f"Generated profile listing at {generated_file} with {len(active_slugs)} entries.")

if __name__ == "__main__":
    main()
