import os
import re
import shutil

projects_dir = r"D:\map12\public\projects"
manifest_path = r"D:\map12\src\data\project-images.ts"

# 1. Renames for specific folders
renames = {
    "Dejoya Residence": "dejoya-residence",
    "Ras Sudr Riviera": "ras-sudr-riviera",
    "dose": "d-o-s-e",
    "hap-town": "haptown"
}

for src, dst in renames.items():
    src_path = os.path.join(projects_dir, src)
    dst_path = os.path.join(projects_dir, dst)
    if os.path.exists(src_path):
        if os.path.exists(dst_path):
            # Move files from src to dst
            for f in os.listdir(src_path):
                f_src = os.path.join(src_path, f)
                f_dst = os.path.join(dst_path, f)
                if not os.path.exists(f_dst):
                    shutil.move(f_src, f_dst)
            shutil.rmtree(src_path)
            print(f"Merged {src} into {dst}")
        else:
            os.rename(src_path, dst_path)
            print(f"Renamed {src} to {dst}")

# 2. Merge common-haus and commonhaus
common_haus_path = os.path.join(projects_dir, "common-haus")
commonhaus_path = os.path.join(projects_dir, "commonhaus")
if os.path.exists(common_haus_path):
    if os.path.exists(commonhaus_path):
        for f in os.listdir(common_haus_path):
            f_src = os.path.join(common_haus_path, f)
            f_dst = os.path.join(commonhaus_path, f)
            if not os.path.exists(f_dst):
                shutil.move(f_src, f_dst)
        shutil.rmtree(common_haus_path)
        print("Merged common-haus into commonhaus")
    else:
        os.rename(common_haus_path, commonhaus_path)
        print("Renamed common-haus to commonhaus")

# 3. Scan and regenerate manifest
counts = {}
for d in sorted(os.listdir(projects_dir)):
    dpath = os.path.join(projects_dir, d)
    if os.path.isdir(dpath):
        # Find all images
        files = []
        for f in os.listdir(dpath):
            if f.lower().endswith(('.jpg', '.jpeg', '.png', '.webp')) and 'master' not in f.lower():
                files.append(f)
        
        # Sort files numerically if they start with a number
        def sort_key(name):
            match = re.match(r"^(\d+)", name)
            if match:
                return (0, int(match.group(1)), name.lower())
            return (1, name.lower())
            
        files.sort(key=sort_key)
        
        if files:
            # We want to format the paths as relative to public folder, e.g. /projects/slug/1.jpg
            # Let's verify files are named 1.jpg, 2.jpg etc.
            # To keep it robust, we'll keep the actual filenames!
            counts[d] = [f"/projects/{d}/{f}" for f in files]

# 4. Write manifest
lines = [
    "// Auto-generated by scripts/sync_all_project_images.py",
    "",
    "export const projectImages: Record<string, string[]> = {"
]

for slug in sorted(counts):
    img_list = counts[slug]
    paths_str = ", ".join(f'"{p}"' for p in img_list)
    lines.append(f'  "{slug}": [{paths_str}],')

lines.append("};")
lines.append("")

with open(manifest_path, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print(f"Successfully generated project-images.ts with {len(counts)} compounds!")
