import fs from "node:fs";
import path from "node:path";

const projectImagesPath = path.join(process.cwd(), "src", "data", "project-images.ts");
let content = fs.readFileSync(projectImagesPath, "utf-8");

// Parse projectImages object by evaluating code safely in node context
const jsonMatch = content.match(
  /export const projectImages: Record<string, string\[\]> = ([\s\S]*?);/,
);
if (!jsonMatch) {
  console.error("Could not find projectImages definition");
  process.exit(1);
}

const objText = jsonMatch[1];
const projectImages = eval(`(${objText})`);

// 1. Azha North Coast
projectImages["azha-north-coast"] = [
  "/projects/azha-north-coast/1.jpg",
  "/projects/azha-north-coast/2.jpg",
  "/projects/azha-north-coast/3.jpg",
  "/projects/azha-north-coast/4.jpg",
  "/projects/azha-north-coast/5.jpg",
  "/projects/azha-north-coast/6.jpg",
  "/projects/azha-north-coast/7.jpg",
  "/projects/azha-north-coast/8.jpg",
  "/projects/azha-north-coast/9.jpg",
  "/projects/azha-north-coast/10.jpg",
];
projectImages["elea-azha-north"] = projectImages["azha-north-coast"];

// 2. Salt Marina
projectImages["salt-marina"] = ["/projects/salt-marina/1.jpg"];

// 3. Perla
projectImages["perla"] = ["/projects/perla/1.jpg"];

// 4. Bloom Island Ogami (from Ogami)
if (projectImages["ogami"]) {
  projectImages["bloom-island-ogami"] = projectImages["ogami"];
  projectImages["bloom-island"] = projectImages["ogami"];
}

// 5. Saada North Coast (from Saada Sahel)
if (projectImages["saada-sahel"]) {
  projectImages["saada-north-coast"] = projectImages["saada-sahel"];
  projectImages["saada"] = projectImages["saada-sahel"];
}

// 6. Vie
projectImages["vie"] = ["/projects/vie/1.jpg"];
projectImages["vie-collective"] = ["/projects/vie/1.jpg"];
projectImages["vie-halo"] = ["/projects/vie/1.jpg"];
projectImages["vye-sodic"] = ["/projects/vie/1.jpg"];

// Reformat back to TypeScript
const updatedText = `// Auto-generated by scripts/sync_all_project_images.py\n\nexport const projectImages: Record<string, string[]> = ${JSON.stringify(projectImages, null, 2)};\n`;

fs.writeFileSync(projectImagesPath, updatedText, "utf-8");
console.log("Successfully updated src/data/project-images.ts");
