/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as MapRouteImport } from './routes/map'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as AreasRouteImport } from './routes/areas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as DevelopersSlugRouteImport } from './routes/developers.$slug'
import { Route as AreasSlugRouteImport } from './routes/areas.$slug'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasRoute = AreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const DevelopersSlugRoute = DevelopersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DevelopersRoute,
} as any)
const AreasSlugRoute = AreasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AreasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/areas': typeof AreasRouteWithChildren
  '/developers': typeof DevelopersRouteWithChildren
  '/map': typeof MapRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/areas/$slug': typeof AreasSlugRoute
  '/developers/$slug': typeof DevelopersSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/areas': typeof AreasRouteWithChildren
  '/developers': typeof DevelopersRouteWithChildren
  '/map': typeof MapRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/areas/$slug': typeof AreasSlugRoute
  '/developers/$slug': typeof DevelopersSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/areas': typeof AreasRouteWithChildren
  '/developers': typeof DevelopersRouteWithChildren
  '/map': typeof MapRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/areas/$slug': typeof AreasSlugRoute
  '/developers/$slug': typeof DevelopersSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/areas'
    | '/developers'
    | '/map'
    | '/projects'
    | '/areas/$slug'
    | '/developers/$slug'
    | '/projects/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/areas'
    | '/developers'
    | '/map'
    | '/projects'
    | '/areas/$slug'
    | '/developers/$slug'
    | '/projects/$slug'
  id:
    | '__root__'
    | '/'
    | '/areas'
    | '/developers'
    | '/map'
    | '/projects'
    | '/areas/$slug'
    | '/developers/$slug'
    | '/projects/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreasRoute: typeof AreasRouteWithChildren
  DevelopersRoute: typeof DevelopersRouteWithChildren
  MapRoute: typeof MapRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas': {
      id: '/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/developers/$slug': {
      id: '/developers/$slug'
      path: '/$slug'
      fullPath: '/developers/$slug'
      preLoaderRoute: typeof DevelopersSlugRouteImport
      parentRoute: typeof DevelopersRoute
    }
    '/areas/$slug': {
      id: '/areas/$slug'
      path: '/$slug'
      fullPath: '/areas/$slug'
      preLoaderRoute: typeof AreasSlugRouteImport
      parentRoute: typeof AreasRoute
    }
  }
}

interface AreasRouteChildren {
  AreasSlugRoute: typeof AreasSlugRoute
}

const AreasRouteChildren: AreasRouteChildren = {
  AreasSlugRoute: AreasSlugRoute,
}

const AreasRouteWithChildren = AreasRoute._addFileChildren(AreasRouteChildren)

interface DevelopersRouteChildren {
  DevelopersSlugRoute: typeof DevelopersSlugRoute
}

const DevelopersRouteChildren: DevelopersRouteChildren = {
  DevelopersSlugRoute: DevelopersSlugRoute,
}

const DevelopersRouteWithChildren = DevelopersRoute._addFileChildren(
  DevelopersRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreasRoute: AreasRouteWithChildren,
  DevelopersRoute: DevelopersRouteWithChildren,
  MapRoute: MapRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
