/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as NewLaunchesRouteImport } from './routes/new-launches'
import { Route as MapRouteImport } from './routes/map'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as DeveloperPartnershipRouteImport } from './routes/developer-partnership'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgencyPartnershipRouteImport } from './routes/agency-partnership'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as DevelopersIndexRouteImport } from './routes/developers.index'
import { Route as DestinationsIndexRouteImport } from './routes/destinations.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as DevelopersSlugRouteImport } from './routes/developers.$slug'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as DashboardTeamRouteImport } from './routes/dashboard.team'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardMapsRouteImport } from './routes/dashboard.maps'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard.leads'
import { Route as DashboardFavoritesRouteImport } from './routes/dashboard.favorites'
import { Route as DashboardCompareRouteImport } from './routes/dashboard.compare'
import { Route as DashboardCampaignsRouteImport } from './routes/dashboard.campaigns'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as DashboardAiAssistantRouteImport } from './routes/dashboard.ai-assistant'
import { Route as ApiUploadAssetRouteImport } from './routes/api.upload-asset'
import { Route as ApiSaveUsersRouteImport } from './routes/api.save-users'
import { Route as ApiSaveDatabaseRouteImport } from './routes/api.save-database'
import { Route as ApiBrochuresMatchRouteImport } from './routes/api.brochures-match'
import { Route as UnitsProjectSlugTypeSlugRouteImport } from './routes/units.$projectSlug.$typeSlug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const NewLaunchesRoute = NewLaunchesRouteImport.update({
  id: '/new-launches',
  path: '/new-launches',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperPartnershipRoute = DeveloperPartnershipRouteImport.update({
  id: '/developer-partnership',
  path: '/developer-partnership',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyPartnershipRoute = AgencyPartnershipRouteImport.update({
  id: '/agency-partnership',
  path: '/agency-partnership',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const DevelopersIndexRoute = DevelopersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevelopersRoute,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DestinationsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const DevelopersSlugRoute = DevelopersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DevelopersRoute,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DestinationsRoute,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMapsRoute = DashboardMapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFavoritesRoute = DashboardFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCompareRoute = DashboardCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCampaignsRoute = DashboardCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiAssistantRoute = DashboardAiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiUploadAssetRoute = ApiUploadAssetRouteImport.update({
  id: '/api/upload-asset',
  path: '/api/upload-asset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaveUsersRoute = ApiSaveUsersRouteImport.update({
  id: '/api/save-users',
  path: '/api/save-users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaveDatabaseRoute = ApiSaveDatabaseRouteImport.update({
  id: '/api/save-database',
  path: '/api/save-database',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrochuresMatchRoute = ApiBrochuresMatchRouteImport.update({
  id: '/api/brochures-match',
  path: '/api/brochures-match',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsProjectSlugTypeSlugRoute =
  UnitsProjectSlugTypeSlugRouteImport.update({
    id: '/units/$projectSlug/$typeSlug',
    path: '/units/$projectSlug/$typeSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agency-partnership': typeof AgencyPartnershipRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/destinations': typeof DestinationsRouteWithChildren
  '/developer-partnership': typeof DeveloperPartnershipRoute
  '/developers': typeof DevelopersRouteWithChildren
  '/map': typeof MapRoute
  '/new-launches': typeof NewLaunchesRoute
  '/pricing': typeof PricingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/brochures-match': typeof ApiBrochuresMatchRoute
  '/api/save-database': typeof ApiSaveDatabaseRoute
  '/api/save-users': typeof ApiSaveUsersRoute
  '/api/upload-asset': typeof ApiUploadAssetRoute
  '/dashboard/ai-assistant': typeof DashboardAiAssistantRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/compare': typeof DashboardCompareRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/maps': typeof DashboardMapsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/developers/$slug': typeof DevelopersSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/developers/': typeof DevelopersIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/units/$projectSlug/$typeSlug': typeof UnitsProjectSlugTypeSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agency-partnership': typeof AgencyPartnershipRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/developer-partnership': typeof DeveloperPartnershipRoute
  '/map': typeof MapRoute
  '/new-launches': typeof NewLaunchesRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/brochures-match': typeof ApiBrochuresMatchRoute
  '/api/save-database': typeof ApiSaveDatabaseRoute
  '/api/save-users': typeof ApiSaveUsersRoute
  '/api/upload-asset': typeof ApiUploadAssetRoute
  '/dashboard/ai-assistant': typeof DashboardAiAssistantRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/compare': typeof DashboardCompareRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/maps': typeof DashboardMapsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/developers/$slug': typeof DevelopersSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/dashboard': typeof DashboardIndexRoute
  '/destinations': typeof DestinationsIndexRoute
  '/developers': typeof DevelopersIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/units/$projectSlug/$typeSlug': typeof UnitsProjectSlugTypeSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agency-partnership': typeof AgencyPartnershipRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/destinations': typeof DestinationsRouteWithChildren
  '/developer-partnership': typeof DeveloperPartnershipRoute
  '/developers': typeof DevelopersRouteWithChildren
  '/map': typeof MapRoute
  '/new-launches': typeof NewLaunchesRoute
  '/pricing': typeof PricingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/brochures-match': typeof ApiBrochuresMatchRoute
  '/api/save-database': typeof ApiSaveDatabaseRoute
  '/api/save-users': typeof ApiSaveUsersRoute
  '/api/upload-asset': typeof ApiUploadAssetRoute
  '/dashboard/ai-assistant': typeof DashboardAiAssistantRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/compare': typeof DashboardCompareRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/maps': typeof DashboardMapsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/developers/$slug': typeof DevelopersSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/developers/': typeof DevelopersIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/units/$projectSlug/$typeSlug': typeof UnitsProjectSlugTypeSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/agency-partnership'
    | '/auth'
    | '/calculator'
    | '/compare'
    | '/contact'
    | '/dashboard'
    | '/destinations'
    | '/developer-partnership'
    | '/developers'
    | '/map'
    | '/new-launches'
    | '/pricing'
    | '/projects'
    | '/sitemap.xml'
    | '/api/brochures-match'
    | '/api/save-database'
    | '/api/save-users'
    | '/api/upload-asset'
    | '/dashboard/ai-assistant'
    | '/dashboard/billing'
    | '/dashboard/campaigns'
    | '/dashboard/compare'
    | '/dashboard/favorites'
    | '/dashboard/leads'
    | '/dashboard/maps'
    | '/dashboard/profile'
    | '/dashboard/team'
    | '/destinations/$slug'
    | '/developers/$slug'
    | '/projects/$slug'
    | '/dashboard/'
    | '/destinations/'
    | '/developers/'
    | '/projects/'
    | '/units/$projectSlug/$typeSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/agency-partnership'
    | '/auth'
    | '/calculator'
    | '/compare'
    | '/contact'
    | '/developer-partnership'
    | '/map'
    | '/new-launches'
    | '/pricing'
    | '/sitemap.xml'
    | '/api/brochures-match'
    | '/api/save-database'
    | '/api/save-users'
    | '/api/upload-asset'
    | '/dashboard/ai-assistant'
    | '/dashboard/billing'
    | '/dashboard/campaigns'
    | '/dashboard/compare'
    | '/dashboard/favorites'
    | '/dashboard/leads'
    | '/dashboard/maps'
    | '/dashboard/profile'
    | '/dashboard/team'
    | '/destinations/$slug'
    | '/developers/$slug'
    | '/projects/$slug'
    | '/dashboard'
    | '/destinations'
    | '/developers'
    | '/projects'
    | '/units/$projectSlug/$typeSlug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/agency-partnership'
    | '/auth'
    | '/calculator'
    | '/compare'
    | '/contact'
    | '/dashboard'
    | '/destinations'
    | '/developer-partnership'
    | '/developers'
    | '/map'
    | '/new-launches'
    | '/pricing'
    | '/projects'
    | '/sitemap.xml'
    | '/api/brochures-match'
    | '/api/save-database'
    | '/api/save-users'
    | '/api/upload-asset'
    | '/dashboard/ai-assistant'
    | '/dashboard/billing'
    | '/dashboard/campaigns'
    | '/dashboard/compare'
    | '/dashboard/favorites'
    | '/dashboard/leads'
    | '/dashboard/maps'
    | '/dashboard/profile'
    | '/dashboard/team'
    | '/destinations/$slug'
    | '/developers/$slug'
    | '/projects/$slug'
    | '/dashboard/'
    | '/destinations/'
    | '/developers/'
    | '/projects/'
    | '/units/$projectSlug/$typeSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AgencyPartnershipRoute: typeof AgencyPartnershipRoute
  AuthRoute: typeof AuthRoute
  CalculatorRoute: typeof CalculatorRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DestinationsRoute: typeof DestinationsRouteWithChildren
  DeveloperPartnershipRoute: typeof DeveloperPartnershipRoute
  DevelopersRoute: typeof DevelopersRouteWithChildren
  MapRoute: typeof MapRoute
  NewLaunchesRoute: typeof NewLaunchesRoute
  PricingRoute: typeof PricingRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiBrochuresMatchRoute: typeof ApiBrochuresMatchRoute
  ApiSaveDatabaseRoute: typeof ApiSaveDatabaseRoute
  ApiSaveUsersRoute: typeof ApiSaveUsersRoute
  ApiUploadAssetRoute: typeof ApiUploadAssetRoute
  UnitsProjectSlugTypeSlugRoute: typeof UnitsProjectSlugTypeSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-launches': {
      id: '/new-launches'
      path: '/new-launches'
      fullPath: '/new-launches'
      preLoaderRoute: typeof NewLaunchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer-partnership': {
      id: '/developer-partnership'
      path: '/developer-partnership'
      fullPath: '/developer-partnership'
      preLoaderRoute: typeof DeveloperPartnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency-partnership': {
      id: '/agency-partnership'
      path: '/agency-partnership'
      fullPath: '/agency-partnership'
      preLoaderRoute: typeof AgencyPartnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/developers/': {
      id: '/developers/'
      path: '/'
      fullPath: '/developers/'
      preLoaderRoute: typeof DevelopersIndexRouteImport
      parentRoute: typeof DevelopersRoute
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof DestinationsRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/developers/$slug': {
      id: '/developers/$slug'
      path: '/$slug'
      fullPath: '/developers/$slug'
      preLoaderRoute: typeof DevelopersSlugRouteImport
      parentRoute: typeof DevelopersRoute
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof DestinationsRoute
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/maps': {
      id: '/dashboard/maps'
      path: '/maps'
      fullPath: '/dashboard/maps'
      preLoaderRoute: typeof DashboardMapsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/favorites': {
      id: '/dashboard/favorites'
      path: '/favorites'
      fullPath: '/dashboard/favorites'
      preLoaderRoute: typeof DashboardFavoritesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/compare': {
      id: '/dashboard/compare'
      path: '/compare'
      fullPath: '/dashboard/compare'
      preLoaderRoute: typeof DashboardCompareRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/campaigns': {
      id: '/dashboard/campaigns'
      path: '/campaigns'
      fullPath: '/dashboard/campaigns'
      preLoaderRoute: typeof DashboardCampaignsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai-assistant': {
      id: '/dashboard/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/dashboard/ai-assistant'
      preLoaderRoute: typeof DashboardAiAssistantRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/upload-asset': {
      id: '/api/upload-asset'
      path: '/api/upload-asset'
      fullPath: '/api/upload-asset'
      preLoaderRoute: typeof ApiUploadAssetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/save-users': {
      id: '/api/save-users'
      path: '/api/save-users'
      fullPath: '/api/save-users'
      preLoaderRoute: typeof ApiSaveUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/save-database': {
      id: '/api/save-database'
      path: '/api/save-database'
      fullPath: '/api/save-database'
      preLoaderRoute: typeof ApiSaveDatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brochures-match': {
      id: '/api/brochures-match'
      path: '/api/brochures-match'
      fullPath: '/api/brochures-match'
      preLoaderRoute: typeof ApiBrochuresMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units/$projectSlug/$typeSlug': {
      id: '/units/$projectSlug/$typeSlug'
      path: '/units/$projectSlug/$typeSlug'
      fullPath: '/units/$projectSlug/$typeSlug'
      preLoaderRoute: typeof UnitsProjectSlugTypeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAiAssistantRoute: typeof DashboardAiAssistantRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardCampaignsRoute: typeof DashboardCampaignsRoute
  DashboardCompareRoute: typeof DashboardCompareRoute
  DashboardFavoritesRoute: typeof DashboardFavoritesRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardMapsRoute: typeof DashboardMapsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiAssistantRoute: DashboardAiAssistantRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardCampaignsRoute: DashboardCampaignsRoute,
  DashboardCompareRoute: DashboardCompareRoute,
  DashboardFavoritesRoute: DashboardFavoritesRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardMapsRoute: DashboardMapsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DestinationsRouteChildren {
  DestinationsSlugRoute: typeof DestinationsSlugRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
}

const DestinationsRouteChildren: DestinationsRouteChildren = {
  DestinationsSlugRoute: DestinationsSlugRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
}

const DestinationsRouteWithChildren = DestinationsRoute._addFileChildren(
  DestinationsRouteChildren,
)

interface DevelopersRouteChildren {
  DevelopersSlugRoute: typeof DevelopersSlugRoute
  DevelopersIndexRoute: typeof DevelopersIndexRoute
}

const DevelopersRouteChildren: DevelopersRouteChildren = {
  DevelopersSlugRoute: DevelopersSlugRoute,
  DevelopersIndexRoute: DevelopersIndexRoute,
}

const DevelopersRouteWithChildren = DevelopersRoute._addFileChildren(
  DevelopersRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AgencyPartnershipRoute: AgencyPartnershipRoute,
  AuthRoute: AuthRoute,
  CalculatorRoute: CalculatorRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DestinationsRoute: DestinationsRouteWithChildren,
  DeveloperPartnershipRoute: DeveloperPartnershipRoute,
  DevelopersRoute: DevelopersRouteWithChildren,
  MapRoute: MapRoute,
  NewLaunchesRoute: NewLaunchesRoute,
  PricingRoute: PricingRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiBrochuresMatchRoute: ApiBrochuresMatchRoute,
  ApiSaveDatabaseRoute: ApiSaveDatabaseRoute,
  ApiSaveUsersRoute: ApiSaveUsersRoute,
  ApiUploadAssetRoute: ApiUploadAssetRoute,
  UnitsProjectSlugTypeSlugRoute: UnitsProjectSlugTypeSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
