// Auto-generated by scripts/copy-profiles.py - do not edit by hand.
export const developersWithProfiles: string[] = ['hassan-allam-properties', 'hyde-park', 'la-vista-developments', 'lmd', 'madinet-masr', 'misr-italia', 'ora-developers', 'sodic', 'tatweer-misr', 'the-waterway-developments'];
